import { Dimensions, StyleSheet } from 'react-native';
import theme from '../../../config/theme';
const styles = StyleSheet.create({
  wrapper: {
    height: '100%',
    backgroundColor: theme.colors.black,
    display: 'flex',
    flexDirection: 'column',
  },
  listFriendWithoutAccount: {
    flex: 1,
  },
  listFriendWithAccount: {
    marginTop: '1%',
    flex: 1,
  },
  header: {
    backgroundColor: 'rgba(217, 217, 217, 0.19)',
    height: '20%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    marginStart: '6%',
    fontWeight: 700,
    fontSize: theme.fontSizes.text_body,
    color: theme.colors.quaternary,
    flex: 1,
  },
  btnAdd: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.colors.quaternary,
    margin: '2.5%',
    marginEnd: '5%',
    backgroundColor: 'rgba(253, 133, 219, 0.22)',
    height: '80%',
    width: '24%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAddFriend: {
    color: theme.colors.white,
    fontSize: theme.colors.text_body,
  },
  modalView: {
    width: '100%',
    height: 380,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    elevation: 5,
  },
  modalViewTop: {
    width: '100%',
    height: 380,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 35,
    elevation: 5,
  },
  closeModal: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  modalLabel: {
    fontSize: theme.fontSizes.text_body,
    fontWeight: 500,
  },
  modalInput: {
    height: 50,
    backgroundColor: '#e5e5e5',
    borderRadius: 15,
    paddingHorizontal: 10,
    marginBottom: 20,
    marginTop: 5,
  },
  btnSave: {
    backgroundColor: theme.colors.quaternary,
    width: Dimensions.get('window').width * 0.7,
    marginHorizontal: '8%',
    marginTop: '30%',
    height: 60,
    borderRadius: 10,
    padding: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAddNew: {
    color: theme.colors.white,
    fontWeight: 400,
    fontSize: theme.fontSizes.text_body,
  },
  modalContent: {
    flex: 1,
    justifyContent: 'center',
  },
  modalView1: {
    width: '100%',
    height: Dimensions.get('window').height * 0.6,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    elevation: 5,
  },
  modalViewTop1: {
    width: '100%',
    height: Dimensions.get('window').height * 0.6,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 35,
    paddingTop: '20%',
    elevation: 5,
  },
  bottomView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginStart: '-4%',
  },
  searchIcon: {
    marginRight: '4%',
    fontSize: 28,
    color: theme.colors.quaternary,
    zIndex: 999,
  },
  modalInput1: {
    width: '90%',
    height: 50,
    backgroundColor: '#e5e5e5',
    borderRadius: 15,
    paddingStart: 60,
    paddingLeft: 60,
    marginStart: '-15%',
    marginBottom: '3%',
    marginTop: '1%',
  },
  modalContent1: {
    marginHorizontal: '-6%',
    marginLeft: '3%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  centeredComponent: {
    alignItems: 'center',
  },
});

export default styles;
